In [1]:
list=[1,2,3]

In [2]:
list

[1, 2, 3]

In [3]:
import numpy as np
arr=np.array(list)
arr

array([1, 2, 3])

In [4]:
np.ones(3,5) 

array([1., 1., 1.])

In [5]:
np.eyes(5,5)

AttributeError: module 'numpy' has no attribute 'eyes'

In [8]:
ar=random.randint(1,100)

In [9]:
ar=random.randint(1,100)

NameError: name 'random' is not defined

In [10]:
np.random.randint(1,100)

54

In [11]:
np.random.randint(1,100)

array([78, 78, 53, 40, 13,  7, 99, 47, 79, 68])

In [12]:
np.random.randint(1,100)

84

In [14]:
np.linspace(0,50,48)

array([ 0.        ,  1.06382979,  2.12765957,  3.19148936,  4.25531915,
        5.31914894,  6.38297872,  7.44680851,  8.5106383 ,  9.57446809,
       10.63829787, 11.70212766, 12.76595745, 13.82978723, 14.89361702,
       15.95744681, 17.0212766 , 18.08510638, 19.14893617, 20.21276596,
       21.27659574, 22.34042553, 23.40425532, 24.46808511, 25.53191489,
       26.59574468, 27.65957447, 28.72340426, 29.78723404, 30.85106383,
       31.91489362, 32.9787234 , 34.04255319, 35.10638298, 36.17021277,
       37.23404255, 38.29787234, 39.36170213, 40.42553191, 41.4893617 ,
       42.55319149, 43.61702128, 44.68085106, 45.74468085, 46.80851064,
       47.87234043, 48.93617021, 50.        ])

In [15]:
arr2=np.arange(50).reshape(5,10)

In [16]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
arr2[2][1:6]

array([21, 22, 23, 24, 25])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
arr=np.zeros(10)
arr[:]=5

In [24]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [26]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [31]:
import pandas as pd
from numpy.random import randn

In [32]:
df=pd.DataFrame(randn(3,3),['A','B','C'],[1,2,3])

In [33]:
df

1         2         3
A  0.236681  0.583287 -0.561186
B -0.454322  0.757405  1.050681
C  0.991743  0.171691 -0.080425

In [34]:
df.A


AttributeError: 'DataFrame' object has no attribute 'A'

In [35]:
df['A']

KeyError: 'A'

In [36]:
df[1]

A    0.236681
B   -0.454322
C    0.991743
Name: 1, dtype: float64

In [37]:
df[:]['A']

KeyError: 'A'

In [38]:
df[[1,3]]

1         3
A  0.236681 -0.561186
B -0.454322  1.050681
C  0.991743 -0.080425

In [39]:
df[4]=df[2]+df[1]

In [40]:
df

1         2         3         4
A  0.236681  0.583287 -0.561186  0.819967
B -0.454322  0.757405  1.050681  0.303083
C  0.991743  0.171691 -0.080425  1.163434

In [41]:
df.drop[4]

TypeError: 'method' object is not subscriptable

In [42]:
df.drop(4)

KeyError: '[4] not found in axis'

In [43]:
df.drop('A')

1         2         3         4
B -0.454322  0.757405  1.050681  0.303083
C  0.991743  0.171691 -0.080425  1.163434

In [49]:
df.drop(2,axis=1,inplace=False)

KeyError: '[2] not found in axis'

In [52]:
df


1         3         4
A  0.236681 -0.561186  0.819967
B -0.454322  1.050681  0.303083
C  0.991743 -0.080425  1.163434

In [53]:
df

1         3         4
A  0.236681 -0.561186  0.819967
B -0.454322  1.050681  0.303083
C  0.991743 -0.080425  1.163434

In [51]:
df.shape

(3, 3)

In [56]:
df.iloc[:3,:2]

1         3
A  0.236681 -0.561186
B -0.454322  1.050681
C  0.991743 -0.080425

In [57]:
df.rename[3]=2

TypeError: 'method' object does not support item assignment

In [58]:
df

1         3         4
A  0.236681 -0.561186  0.819967
B -0.454322  1.050681  0.303083
C  0.991743 -0.080425  1.163434

In [63]:
df[df>0][3]

A         NaN
B    1.050681
C         NaN
Name: 3, dtype: float64

In [64]:
df.index=['p','q','r']

In [65]:
df

1         3         4
p  0.236681 -0.561186  0.819967
q -0.454322  1.050681  0.303083
r  0.991743 -0.080425  1.163434

In [69]:
from numpy.random import randn
arr1=randn(1,3)
arr2=randn(1,3)
arr3=randn(1,3)


In [70]:
arr1

array([[ 1.48091918, -1.28928314, -0.54438908]])

In [78]:
dict={'A':arr1np.random.randint(1,100)np.random.randint(1,100),'B':[5,6,7,8],'C':[9,10,11,12]}

In [79]:
df2=pd.DataFrame(dict)

ValueError: Per-column arrays must each be 1-dimensional

In [80]:
df2

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [76]:
df2.transpose()

0   1   2   3
A  1   2   3   4
B  5   6   7   8
C  9  10  11  12

In [77]:
df.join(df2)

1         3         4   A   B   C
p  0.236681 -0.561186  0.819967 NaN NaN NaN
q -0.454322  1.050681  0.303083 NaN NaN NaN
r  0.991743 -0.080425  1.163434 NaN NaN NaN

In [82]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

In [83]:
df


col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [84]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [85]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [86]:
df2.pivot_table(values='D',index=['A', 'B'],columns=['3'])

KeyError: 'D'

In [90]:
df2['D']=np.random.randint(1,10,4)

In [91]:
df2

A  B   C  col4  D
0  1  5   9     6  6
1  2  6  10     4  9
2  3  7  11     3  9
3  4  8  12     6  7

In [100]:
df.drop('col4',axis=1,inplace=True)

KeyError: "['col4'] not found in axis"

In [102]:
df2.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C     9    10   11   12
A B                    
1 5  6.0  NaN  NaN  NaN
2 6  NaN  9.0  NaN  NaN
3 7  NaN  NaN  9.0  NaN
4 8  NaN  NaN  NaN  7.0

In [2]:
import pandas as pd
df = pd.read_csv('example')

FileNotFoundError: [Errno 2] No such file or directory: 'example'

In [3]:
pwd

'C:\\Users\\amish'

In [7]:
df=pd.read_csv('example')

In [8]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [32]:

df.set_index('a',inplace=False)

KeyError: "None of ['a'] are in the columns"

In [29]:
A

0     0
1     4
2     8
3    12
Name: a, dtype: int64

In [15]:
df['a'].mean()

6.0

In [19]:
df['b'].max()


13

In [20]:
pwd

'C:\\Users\\amish'

In [21]:
df=pd.read_csv('Salaries.csv')

In [22]:
df

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [33]:
df[df['EmployeeName']=='JOSEPH DRISCOLL']['JobTitle']
   

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [34]:
df[df['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [43]:
df[df['TotalPayBenefits']==df['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [45]:
df.groupby('Year').mean()['BasePay']

C:\Users\amish\AppData\Local\Temp\ipykernel_20412\40158212.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Year').mean()['BasePay']


Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [6]:
df['JobTitle'].nunique()

NameError: name 'df' is not defined

In [5]:
df['JobTitle'].value_counts().head(5)

NameError: name 'df' is not defined

NameError: name 'df' is not defined